name: Testing context variables 
#type: context variables from GitHub Metadata
on:
  workflow_dispatch

env: 
  cloud: google-cloud

jobs:
  test_context_variables:
    runs-on: ubuntu-latest
    steps: 
      - name: "Checking Context Variables"
        run: |
          echo "Repository Name : ${{ github.repository }}"
          echo "Workflow Name : ${{ github.workflow }}"
          echo "Triggered by : ${{ github.triggering_actor }}"  
