name: Testing Secret Variables
#type: Secrets 
on: 
  workflow_dispatch
env:
  ACTIONS_STEP_DEBUG: true
  jobs:
    test_secrets_variables:
      runs-on: ubuntu:latest
      steps: 
        - name: "Checking Secret Variables"
          run: |
            echo "Secret Value : ${{ secrets.MY_KEY }}"
